version: '3'
services:
   jenkins:
      build: .
      privileged: true
      volumes:
        - /opt/docker/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
      ports:
        - 8080:8080
        - 50000:50000
