version: '3'
services:
   jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      volumes:
        - /opt/docker/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
      ports:
        - 8080:8080
        - 50000:50000
      environment:
        DOCKER_SOCKET: /var/run/docker.sock
        DOCKER_GROUP: dockerhost
        JENKINS_USER: jenkins
        DOCKER_HOST: tcp://10.67.132.181:4243
