FROM alpine:latest

LABEL maintainer="anton.feldmann@gmail.com"
LABEL version="0.1"
LABEL description="This is my basic alpine image based on\
 alpine:latest. This image includes just an ash shell."

	&& rm -rf /var/cache/apk/*

