sudo: required

language: ruby

services:
  - docker

install:
  - docker build -t afeldman/ubuntu:latest --build-arg BASE=ubuntu:latest -f base/ubuntu .
  - docker run -d -p afeldman/ubuntu:latest -c "bash --version"

script:
  - docker ps
