version: '3'
services:
  curlftpfs:
    build:
      context: .
    image: curlftpfs:0.1
    privileged: true
    pid: host
    device:
	- /dev/fuse
    restart: unless-stopped
    volumes:
      - /mnt/ftppoint:/ftp
    environment:
      - FTP=ftp://example.com
      - USER=''
      - PASSWORD=''
      - PORT=21