library: "/opt/beets/library.db"
directory: "/opt/beets/music/"

import:
    write: yes
    copy: no
    move: yes
    delete: no
    link: no
    hardlink: no
    incremental: no
    quiet_fallback: asis
    none_rec_action: ask
    timid: no
    log:
    resume: yes
    group_albums: yes
    autotag: yes
    quiet: yes
    singletons: no
    default_action: apply
    languages: []
    detail: no
    flat: no
    pretend: false
    search_ids: []
    duplicate_action: remove 
    bell: no  

clutter: ["Thumbs.DB", ".DS_Store","*.m3u","*.pls","*.jpg"]
ignore: [".*", "*~", "System Volume Information", "lost+found"]
ignore_hidden: yes

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
path_sep_replace: _
asciify_paths: false
art_filename: cover
max_filename_length: 0

threaded: yes
timeout: 5.0
per_disc_numbering: no
verbose: no
terminal_encoding:
original_date: no
id3v23: no
va_name: "Various Artists"

ui:
    terminal_width: 80
    length_diff_thresh: 10.0
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

format_item: $artist - $album - $title
format_album: $albumartist - $album
time_format: '%Y-%m-%d %H:%M:%S'
format_raw_length: no

sort_album: albumartist+ album+
sort_item: artist+ album+ disc+ track+
sort_case_insensitive: yes

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title

statefile: state.pickle

match:
    strong_rec_thresh: 0.04
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    required: []
    track_length_grace: 10
    track_length_max: 30

plugins: [convert, web, fromfilename, chroma, lastgenre, lyrics, embedart, scrub, mbsync, missing, duplicates]
pluginpath: []

lyrics:
    auto: yes
    fallback: ''

echonest_temp:
    auto: yes

lastgenre:
    whitelist: ~/.config/beets/genre.txt
    canoncical: ~/.config/beets/genres-tree.yaml
    fallback: ''
    source: artist

fetchart:
    auto: yes
    maxwidth: 300
    cautious: true
    cover_names: cover folder

embedart:
    auto: yes
    maxwidth: 300

missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no

duplicates:
    checksum: no  # expensive

replaygain:
    auto: yes
    overwrite: yes
    albumgain: yes

scrub:
    auto: yes

chroma:
    auto: no

convert:
    auto: true
    command: ffmpeg -i $source -y -vn -aq 2 $dest
    extension: mp3

web:
    host: 0.0.0.0
    port: 8337