FROM afeldman/alpine

RUN apk update --no-cache \
    && apk add --no-cache \
       rsync \
       openssh

ENV USER='gentoo_user'

ADD etc/rsyncd.conf /etc/rsyncd.conf
ADD entrypoint.sh /entrypoint.sh

RUN chmod 777 /entrypoint.sh

RUN addgroup -g 1000 ${USER} \
    && adduser -D -h /data -H -S -u 1000 -G ${USER} ${USER} \
    && mkdir /data \
    && chown ${USER}:${USER} /data

WORKDIR /gentoo

EXPOSE 873

ENTRYPOINT ["/entrypoint.sh"]

CMD ["rsyncd"]