version: '3'

services:
  labelimg:
    build: .
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - "/home/$USER:/home/$USER" 
      - "/etc/group:/etc/group:ro" 
      - "/etc/passwd:/etc/passwd:ro" 
      - "/etc/shadow:/etc/shadow:ro" 
      - "/etc/sudoers.d:/etc/sudoers.d:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    working_dir: $DOCKER_WORK_DIR
    user: $DOCKER_USER
    command: labelImg
